### ISSUE TITLE
Main | Header Refactoring

### ISSUE THREAD

**Issue by tiramin** [LIKELION-FE-LAB9/Market-Karly#106]
## 🌳 작업 브랜치
mkk

## 📝 TASK 개요
header 구조 개선 및 링크, 이미지 추가

## ✅ To Do 및 진행상황
- [x] member 카테고리 아이콘 추가
- [x] a 태그 링크 변경
- [x] input 검색 버튼 및 이미지 추가
- [x] 추후 nav 고정을 위해 header-nav 요소를 header__inner 자식 요소에서 header 자식 요소로 이동(header 자식요소로 header__inner, header-nav)
