### ISSUE TITLE
Product-List | Navigator 구현

### ISSUE THREAD

**Issue by ukssss** [LIKELION-FE-LAB9/Market-Karly#148]
# 🌳 작업 브랜치

ukss

# 📝 TASK 개요

Navigator 구현

# ✅ To Do 및 진행상황

- [x] checkbox 구현
- [x] 더보기 버튼 구현
- [x] 초기화 버튼 구현
- [x] 체크항목 수량 표시
