### ISSUE TITLE
Product-List | add-cart 모달창 기능 구현

### ISSUE THREAD

**Issue by ukssss** [LIKELION-FE-LAB9/Market-Karly#172]
# 🌳 작업 브랜치

ukss

# 📝 TASK 개요

모달창 기능 추가 작업

# ✅ To Do 및 진행상황

- [x] 모달창 계산 기능 구현
- [x] 모달창 데이터 불러오기
- [x] 모달창 장바구니 담을 경우 장바구니 상태 변화 나타내기
- [x] 모달창 장바구니 담을 경우 localStorage 추가하기
